[package]
name = "rust-paper-scissors"
version = "0.1.0"
authors = ["Chris <https://github.com/drcsh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"